---
  - name: create application directory for logging
    file:
      path: "{{ appLogsDir }}"
      state: directory
  - name: create application directory for configuration
    file:
      path: "{{ appConfigDir }}"
      state: directory
  - name: copy configuration into config file
    copy:
      src: ./application.properties
      dest: "{{appConfigDir}}"
  - name: install geoserver
    docker_container:
      name: geoserver
      image: "ollihoo/geographicalhierarchygraph:latest"
      pull: yes
      state: started
      restart: yes
      restart_policy: always
      published_ports:
        - "80:8080"
      volumes:
        - "{{ appConfigDir }}:/config"
        - "{{ appLogsDir }}:/logs"