---
- hosts: geoservers
  vars:
    appLogsDir: "/var/run/app/logs"
    appConfigDir: "/var/run/app/config"
    neo4jDataDir: "/var/run/neo4j/data"
    neo4jLogsDir: "/var/run/neo4j/logs"
    neo4jUser: "neo4j"
    neo4jPassword: "iLoveGraphs"
  connection: local
  remote_user: vagrant
  become: true
  become_user: root
  tasks:
  - name: setup infrastructure
    include: ubuntu-basic.yml
  - name: install neo4j
    include: neo4j.yml
  - name: install geoserver
    include: geoserverapplication.yml