---
- hosts: geoservers
  vars:
    appLogsDir: "/var/run/app/logs"
    appConfigDir: "/var/run/app/config"
    neo4jDataDir: "/var/run/neo4j/data"
    neo4jLogsDir: "/var/run/neo4j/logs"
    neo4jUser: "neo4j"
    neo4jPassword: "iLoveGraphs"
  connection: local
  remote_user: vagrant
  become: true
  become_user: root
  roles:
    - bootstrap
    - neo4j
    - webserver