# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.network "forwarded_port", guest: 7474, host: 7474
  config.vm.network "forwarded_port", guest: 7687, host: 7687
  config.vm.synced_folder "logs/", "/var/run/app/logs"
  config.vm.synced_folder "neo4j/", "/var/run/neo4j"

  config.vm.provider "virtualbox" do |v|
       v.memory = 4096
  end

#  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision :ansible_local do |ansible|
       ansible.playbook = "./playbook.yml"
       ansible.inventory_path = "./inventory"
       ansible.verbose        = true
       ansible.install        = true
       ansible.install_mode   = :pip
       ansible.limit          = "geoservers"
  end

end
