version: '2'
services:
  neo4j:
    image: neo4j:latest
    command: mkdir -p /home/neo4j/geodata
    ports:
     - "7474:7474"
    volumes:
     - /home/neo4j/geodata:/data
    expose:
     - "7474"
  webapp:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:8080"
    depends_on:
      - neo4j
