# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 80, host: 10080

  config.vm.provision "docker" do |docker|
      docker.run "ollihoo/geographicalhierarchygraph",
      args: "-p 8080:80 -v /app/logs:/logs  -v /app/config:/config",
      daemonize: true
    end
end
